language: php

php:
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer install

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text
